---
#For all profiles set port 8081
server:
  port: 8081

---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IldarS1995/spring-cloud-config-learning-app
          searchPaths: ConfigData

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:offline-repository/